### ISSUE TITLE
meaning of noci?

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_webtesting#205]
(Sorry that this is a question, not a ticket. Do you have another preferred way of getting questions?)

What's the meaning of the `noci` tag in rules_webtesting? I was using it elsewhere in my own repo for a specific problem and wanted to make sure I'm not stomping on this use case too hard.

**Comment by joshbruning** [comment]
noci = no continuous integration; The test is not intended to be executed in continuous integration. Our CI excludes tests that have this tag. We use it for a wide variety of reasons:
- A target is failing, and not important enough to block workflows required by a passing CI build.
- A target has special requirements that prohibit it from running in a specific CI environment (a test that requires network connectivity to some resource that is not accessible to CI environment, a test with a browser that requires execution on a platform not supported by the CI)

**Comment by jmhodges** [comment]
Ah, that's a bummer because I actually do run my integration tests in CI. What's the safest way to override them? I see that 

```
        "@io_bazel_rules_webtesting//browsers:chromium-native": {
            "local": True,
            "tags": ["noci"],
        },
```

but should I just add `go_test_tags = []` to my `go_web_test_suite` call or remove that tags in the chromium-native bit, too?

I'm kind of surprised that the name I gave my go_web_test_suite doesn't show up in a `bazel query tests(//...)`, btw. I don't really understand how all these things work together.

**Comment by joshbruning** [comment]
Looks like a snippet from browser_overrides - if you're running a test on CI, then you should generally not be tagging a test noci. You should remove the "tags": ["noci"], from your go_web_test_suite definition if it runs on your CI. I don't think there is code that would tag noci on the browser-specific web_test targets unless you explicitly specify that?

Almost no one should have a need to set go_test_tags. That would tag the underlying go_test (the one which each browser-specific web_test points to) which is never supposed to be directly executed by anything.

The name of the suite doesn't appear in the query due to the "manual" tag. It's documented here:
https://docs.bazel.build/versions/master/be/common-definitions.html

**Comment by DrMarcII** [comment]
In browser_overrides, I am including "tags": ["noci"] because I don't want those targets to run. If you want them to run, just don't include that line.

The name you give your go_web_test_suite is not actually used as the name for any test target (although it is used for a test_suite target). go_web_test_suite generates multiple test target, a go_test target with <name>_wrapped that should not be run (and is tagged so that it should not be run), and a web_test target named <name>_<browser> for each browser.
