### ISSUE TITLE
Travis tests for rules_webtesting have been failing for a long time

### ISSUE THREAD

**Issue by irengrig** [bazelbuild/rules_webtesting#343]
Original issue: https://github.com/bazelbuild/bazel/issues/8246

**Comment by hlopko** [comment]
Friendly ping, rules_webtesting have been failing since end of March. It is blocking our (the Bazel team) migrations (e.g. https://github.com/bazelbuild/rules_webtesting/pull/350), we need a green build to ensure this project is fully migrated.

Alternative is to remove rules_webtesting from the Bazel CI downstream pipeline.

@dslomov pls help triage.

**Comment by dslomov** [comment]
Ping @alexeagle @DrMarcII

**Comment by hlopko** [comment]
Duplicate: https://github.com/bazelbuild/rules_webtesting/issues/352.

Tests are still failing today.

**Comment by DrMarcII** [comment]
Fixed as of PR #358
